import { type UUID } from '../types';

// Classifies a raw scanner output into one of three resolution kinds so
// the screen-level dispatchers (/receive, /sell) know which catalogue
// lookup to perform. Pure function; no DB access — repos do the actual
// resolution.
//
// Kinds:
//   * `article_url` — Inventar's own QR shape, an https URL with
//     `/article/{uuid}` in the path. The QR is generated by ArticleQR
//     against the production origin so a printed shelf-label scanned
//     by ANY phone camera opens the article page; the in-app scanner
//     short-circuits to the same article without leaving the screen.
//   * `ean` — looks like a numeric product barcode (EAN-8/12/13/14).
//     The screen still passes the value through useEanValidator so
//     strict-checksum mode keeps working.
//   * `internal_code` — fall-through for everything else, used when a
//     merchant prints their own Code-128 / Code-39 label of an article's
//     short SKU (e.g. "SH-0042"). If lookup fails the screen surfaces
//     a "not found" toast — we never auto-create an article from a
//     non-EAN scan since that would burn a real EAN slot on garbage.

export type ScanResolution =
  | { kind: 'article_url'; articleId: UUID }
  | { kind: 'ean'; value: string }
  | { kind: 'internal_code'; value: string };

const ARTICLE_URL_RE = /^https?:\/\/[^\s]+\/article\/([0-9a-f-]{36})\b/i;
const EAN_SHAPE_RE = /^\d{8,14}$/;

export function classifyScan(raw: string): ScanResolution | null {
  const trimmed = raw.trim();
  if (trimmed === '') return null;
  const urlMatch = ARTICLE_URL_RE.exec(trimmed);
  if (urlMatch?.[1]) return { kind: 'article_url', articleId: urlMatch[1].toLowerCase() };
  if (EAN_SHAPE_RE.test(trimmed)) return { kind: 'ean', value: trimmed };
  // Conservative bound on internal_code so we don't misroute a giant
  // QR payload (e.g. a vCard) into the catalogue lookup. 32 chars is
  // well above what nextInternalCode produces ("SH-0042" = 7 chars).
  if (trimmed.length <= 32) return { kind: 'internal_code', value: trimmed };
  return null;
}
